# Generated by Django 3.2 on 2024-02-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='primary_email',
            new_name='email',
        ),
    ]
